-- First, create 100 word lists
WITH new_word_lists AS (
  INSERT INTO "WordList" ("createdAt", "timesUsed", "lastUsedAt")
  SELECT 
    NOW(),
    0,
    NULL
  FROM generate_series(1, 100)
  RETURNING id
),
-- Real Arabic words (sample list - you should replace with actual Arabic words)
real_words AS (
  SELECT unnest(ARRAY[
    'كتاب', 'قلم', 'مدرسة', 'بيت', 'شجرة', 'سيارة', 'طاولة', 'كرسي', 'باب', 'نافذة',
    'حديقة', 'مكتب', 'هاتف', 'حاسوب', 'ساعة', 'قهوة', 'ماء', 'طعام', 'خبز', 'فاكهة',
    'قطة', 'كلب', 'طائر', 'سمك', 'شمس', 'قمر', 'نجوم', 'سماء', 'بحر', 'جبل',
    'مدينة', 'قرية', 'شارع', 'مطار', 'محطة', 'مستشفى', 'مطعم', 'متجر', 'سوق', 'مكتبة',
    'كتابة', 'قراءة', 'رسم', 'موسيقى', 'رياضة', 'سباحة', 'جري', 'قفز', 'رقص', 'غناء'
  ]) AS word
),
-- Non-words (generated by modifying real words or creating phonologically plausible non-words)
non_words AS (
  SELECT unnest(ARRAY[
    'كتابوش', 'قلمين', 'مدرساب', 'بيتوف', 'شجروت', 'سيارتا', 'طاولوم', 'كرسيف', 'بابوش', 'نافذتا',
    'حديقوت', 'مكتبين', 'هاتفوش', 'حاسبوت', 'ساعتيف', 'قهوتا', 'ماءوش', 'طعامين', 'خبزوت', 'فاكهتا',
    'قطوش', 'كلبين', 'طائروت', 'سمكتا', 'شمسوف', 'قمرين', 'نجموت', 'سماءوش', 'بحروت', 'جبلتا',
    'مدينوش', 'قريتين', 'شارعوت', 'مطارتا', 'محطوف', 'مستشفين', 'مطعموت', 'متجروش', 'سوقتا', 'مكتبوت',
    'كتابتين', 'قراءوش', 'رسموت', 'موسيقتا', 'رياضوف', 'سباحين', 'جريوت', 'قفزتا', 'رقصوش', 'غناءوت'
  ]) AS word
)
-- Insert words for each word list
INSERT INTO "Word" ("word", "isNonWord", "wordListId")
SELECT 
  w.word,
  false,
  wl.id
FROM new_word_lists wl
CROSS JOIN real_words w
UNION ALL
SELECT 
  w.word,
  true,
  wl.id
FROM new_word_lists wl
CROSS JOIN non_words w;
