"use client";

/// Page 1 prof test instructions ///
export const MainFirstInstructions = [
   "ستقرأ 90 كلمة في الاختبار.",
   "بعض هذه الكلمات هي كلمات عربية حقيقية والبعض الآخر كلمات تم تركيبها لتبدو وكأنها كلمات حقيقية.",
   ".فضلاً اختر الكلمات التي تعرفها أو تستطيع استخدامها.",
   "قم بالاختيار بوضع علامة صح بجانب الكلمة.",
   "الاجابة الخاطئة في الاختبار سٌتنقص من درجتك ولهذا فضلاً لا تختر الكلمات التي لاتعرفها. ضع علامة صح بجانب الكلمات التي تعرفها فحسب.",
];

/// Page 2 prof test instructions ///
export const MainSecondInstructions = [
   "الرجاء إكمال الاختبار بمفردك.",
   "الرجاء عدم استخدام القاموس.",
   "خذ وقتك لإكمال الاجابة.",
];

///  "ShortTestInstructions" appears on all prof test pages///
export const ShortTestInstructions = [
   "من فضلك انظر الى هذه الكلمات. بعض هذه الكلمات هي كلمات عربية حقيقية والبعض الآخر كلمات تم تركيبها لتبدو وكأنها كلمات حقيقية. فضلاً اختر الكلمات التي تعرفها أو تستطيع استخدامها. استخدم هذا المثال:",
   "☑ كتاب",
];

export interface Word {
   id: number;
   word: string;
   isReal: boolean;
}

export const wordList: Word[] = [
   { id: 1, word: "تقوية", isReal: true },
   { id: 2, word: "متعمد", isReal: true },
   { id: 3, word: "ارتشف", isReal: true },
   { id: 4, word: "انتكاسة", isReal: true },
   { id: 5, word: "مؤجل", isReal: true },
   { id: 6, word: "متسق", isReal: true },
   { id: 7, word: "انعقاد", isReal: true },
   { id: 8, word: "تكاتف", isReal: true },
   { id: 9, word: "منزوي", isReal: true },
   { id: 10, word: "مفخخ", isReal: true },
   { id: 11, word: "تدنيس", isReal: true },
   { id: 12, word: "تكييف", isReal: true },
   { id: 13, word: "صحوق", isReal: false },
   { id: 14, word: "مواذد", isReal: false },
   { id: 15, word: "جثدية", isReal: false },
   { id: 16, word: "خزاكين", isReal: false },
   { id: 17, word: "تسويع", isReal: false },
   { id: 18, word: "كتاسية", isReal: false },
   { id: 19, word: "صديد", isReal: true },
   { id: 20, word: "خصام", isReal: true },
   { id: 21, word: "تفريغ", isReal: true },
   { id: 22, word: "عتيد", isReal: true },
   { id: 23, word: "ممانعة", isReal: true },
   { id: 24, word: "تقصي", isReal: true },
   { id: 25, word: "سامق", isReal: true },
   { id: 26, word: "لاعب", isReal: true },
   { id: 27, word: "جلجلة", isReal: true },
   { id: 28, word: "متناحرة", isReal: true },
   { id: 29, word: "تزحزح", isReal: true },
   { id: 30, word: "مستعر", isReal: true },
   { id: 31, word: "تغفيش", isReal: false },
   { id: 32, word: "تزذير", isReal: false },
   { id: 33, word: "فتراف", isReal: false },
   { id: 34, word: "ثموح", isReal: false },
   { id: 35, word: "فسغالي", isReal: false },
   { id: 36, word: "سالضين", isReal: false },
   { id: 37, word: "استهل", isReal: true },
   { id: 38, word: "جعجع", isReal: true },
   { id: 39, word: "كبح", isReal: true },
   { id: 40, word: "مقاضاة", isReal: true },
   { id: 41, word: "أعفر", isReal: true },
   { id: 42, word: "خشونة", isReal: true },
   { id: 43, word: "طغى", isReal: true },
   { id: 44, word: "دبيب", isReal: true },
   { id: 45, word: "زورق", isReal: true },
   { id: 46, word: "سؤدد", isReal: true },
   { id: 47, word: "واقي", isReal: true },
   { id: 48, word: "كفكف", isReal: true },
   { id: 49, word: "طعاكة", isReal: false },
   { id: 50, word: "متغقتة", isReal: false },
   { id: 51, word: "هارخة", isReal: false },
   { id: 52, word: "خسم", isReal: false },
   { id: 53, word: "ممتخثين", isReal: false },
   { id: 54, word: "خادثي", isReal: false },
   { id: 55, word: "استوضح", isReal: true },
   { id: 56, word: "صياغة", isReal: true },
   { id: 57, word: "عصف", isReal: true },
   { id: 58, word: "احتجاج", isReal: true },
   { id: 59, word: "أمة", isReal: true },
   { id: 60, word: "وهج", isReal: true },
   { id: 61, word: "مخلب", isReal: true },
   { id: 62, word: "مهشم", isReal: true },
   { id: 63, word: "جثمان", isReal: true },
   { id: 64, word: "طعم", isReal: true },
   { id: 65, word: "اعتناق", isReal: true },
   { id: 66, word: "صيرورة", isReal: true },
   { id: 67, word: "تهاعب", isReal: false },
   { id: 68, word: "تمغيل", isReal: false },
   { id: 69, word: "إشطاقات", isReal: false },
   { id: 70, word: "مسضون", isReal: false },
   { id: 71, word: "سكيم", isReal: false },
   { id: 72, word: "ضماع", isReal: false },
   { id: 73, word: "تنويه", isReal: true },
   { id: 74, word: "تزييف", isReal: true },
   { id: 75, word: "مزاولة", isReal: true },
   { id: 76, word: "متزمت", isReal: true },
   { id: 77, word: "عقاب", isReal: true },
   { id: 78, word: "اجتثاث", isReal: true },
   { id: 79, word: "مسجى", isReal: true },
   { id: 80, word: "فظاظة", isReal: true },
   { id: 81, word: "وجنة", isReal: true },
   { id: 82, word: "ترهل", isReal: true },
   { id: 83, word: "لاذع", isReal: true },
   { id: 84, word: "تناغم", isReal: true },
   { id: 85, word: "مؤشغات", isReal: false },
   { id: 86, word: "مشجكة", isReal: false },
   { id: 87, word: "جاشوزة", isReal: false },
   { id: 88, word: "أعفام", isReal: false },
   { id: 89, word: "أرضلة", isReal: false },
   { id: 90, word: "متحغر", isReal: false },
] as const;
